#!/usr/bin/env bash
# Spec Driver Codex skills 安装/卸载脚本（独立入口）

set -euo pipefail

MODE="project"
ACTION="install"
# Feature 213（A1）：opt-in 双写开关，默认关闭；仅显式 --sync-plugin-distribution 时置 true。
# 只有 repo:sync 的 runStep 传该 flag，避免测试/用户普通 install 误重写 tracked skills-codex/。
SYNC_PLUGIN_DIST="false"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Feature 240（FR-006/007）：全局模式的目标根目录经统一 helper 解析（CODEX_HOME 优先，
# 未设置才 fallback ~/.codex），与 Node 侧 src/core/codex-home.ts 逐字节对拍。
# 🔴 只有 global 分支消费它；project 分支仍以 $PROJECT_ROOT 为基，语义相反，不得混用。
# shellcheck source=lib/codex-home.sh
source "$SCRIPT_DIR/lib/codex-home.sh"

usage() {
  cat <<'USAGE'
用法:
  bash "\$PLUGIN_DIR/scripts/codex-skills.sh" install [--global] [--sync-plugin-distribution]
  bash "\$PLUGIN_DIR/scripts/codex-skills.sh" remove [--global]

说明:
  install                     安装 Spec Driver 的 Codex 包装技能到 .codex/skills
  remove                      移除已安装的 Spec Driver Codex 包装技能
  --global                    目标目录改为 ~/.codex/skills
                              （默认路径，实际以 CODEX_HOME 为准）
  --sync-plugin-distribution  额外把生成结果 copy 到 tracked 的
                              plugins/spec-driver/skills-codex/（随插件包分发）；
                              仅供 npm run repo:sync 使用，普通安装无需该 flag

环境变量:
  CODEX_SKILL_PROJECT_ROOT  覆盖 project 模式的目标项目根目录
USAGE
}

for arg in "$@"; do
  case "$arg" in
    install|remove)
      ACTION="$arg"
      ;;
    --global|-g)
      MODE="global"
      ;;
    --sync-plugin-distribution)
      SYNC_PLUGIN_DIST="true"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[错误] 未知参数: $arg" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ "$MODE" == "global" ]]; then
  # W1 修订：MUST NOT 写成 "$(resolve_codex_home_from_env)/skills" —— CODEX_HOME 带尾斜杠时
  # 会产出 `/tmp/x//skills`，与 Node 侧 join() 的 `/tmp/x/skills` 漂移。
  # resolve_codex_home_subdir 内部经 codex_path_join 吸收尾斜杠与内部 //，与 Node 侧一致。
  TARGET_DIR="$(resolve_codex_home_subdir skills)"
else
  if [[ -n "${CODEX_SKILL_PROJECT_ROOT:-}" ]]; then
    PROJECT_ROOT="$CODEX_SKILL_PROJECT_ROOT"
  elif git -C "$PWD" rev-parse --show-toplevel >/dev/null 2>&1; then
    PROJECT_ROOT="$(git -C "$PWD" rev-parse --show-toplevel)"
  else
    PROJECT_ROOT="$PWD"
  fi
  TARGET_DIR="$PROJECT_ROOT/.codex/skills"
fi

SKILLS=(
  "spec-driver-constitution"
  "spec-driver-feature"
  "spec-driver-implement"
  "spec-driver-story"
  "spec-driver-fix"
  "spec-driver-resume"
  "spec-driver-sync"
  "spec-driver-doc"
  "spec-driver-refactor"
)

ensure_source_exists() {
  local source_skill_path="$1"
  if [[ ! -f "$source_skill_path" ]]; then
    echo "[错误] 找不到 source skill: $source_skill_path" >&2
    exit 1
  fi
}

# F186 T2：原 rewrite_codex_runtime_text（awk|sed 管道的 9 条替换）已迁移到单一 Node helper
# plugins/spec-driver/scripts/lib/extract-wrapper-body.mjs，与 JS 校验端共用，杜绝双实现漂移。

write_frontmatter() {
  local skill_name="$1"
  local source_skill_path="$2"

  awk -v skill_name="$skill_name" '
    NR == 1 && $0 == "---" {
      in_frontmatter = 1
      print
      next
    }
    in_frontmatter {
      if ($0 ~ /^name:[[:space:]]/) {
        print "name: " skill_name
        next
      }
      print
      if ($0 == "---") {
        exit
      }
    }
  ' "$source_skill_path"
}

write_codex_adapter() {
  local skill_name="$1"
  local source_skill_name="$2"
  local source_command="/spec-driver:$source_skill_name"

  cat <<EOF_ADAPTER
## Codex Runtime Adapter

此 Skill 在安装时直接同步自 \`\$PLUGIN_DIR/skills/$source_skill_name/SKILL.md\` 的描述与正文，只额外叠加以下 Codex 运行时差异：

- 命令别名：正文中的 \`$source_command\` 在 Codex 中等价于 \`\$$skill_name\`
- 子代理执行能力：以 install-time 探测记录为准（\`.codex/spec-driver-capability.md\`，全局安装则为 \`~/.codex/spec-driver-capability.md\`（默认路径，实际以 \`CODEX_HOME\` 为准））；记录缺失或 degraded 时，正文中的 \`Task(...)\` / \`Task tool\` 一律按当前会话内联/串行降级执行
- 并行回退：原并行组若当前环境无法并行，必须显式标注 \`[回退:串行]\`
- 模型兼容：遵循 \`model_compat.aliases.codex\` tier 映射优先级（\`--preset -> agents.{agent_id}.model(仅显式配置时生效) -> preset 默认\`）；未显式 pin 时由 Codex CLI 自身按其配置分层（\`-c\` override > profile > \`~/.codex/config.toml\` 的 \`model\` 字段 > CLI 内建默认）决定当前默认模型，不冒充为已验证的具体版本
- 质量门与产物：所有质量门、制品路径、写入边界与 source skill 完全一致，不得弱化或越界

---
EOF_ADAPTER
}

write_wrapper_source_contract() {
  local source_skill_name="$1"
  local source_skill_path="$2"

  # F186 T2：盖印 source body sha256（与 JS 校验端共用同一 helper，杜绝双实现漂移）。
  local body_sha
  body_sha="$(node "$PLUGIN_DIR/scripts/lib/extract-wrapper-body.mjs" "$source_skill_path" --sha256)"

  # CRITICAL-1：helper 在安装路径含空格/非 ASCII 时若 isDirectExecution 误判会输出空 stdout 但退出码 0，
  # 静默生成空 sha → 空 wrapper。此处对非 64 位十六进制 sha 做 hard fail，杜绝静默降级。
  if [[ ! "$body_sha" =~ ^[0-9a-f]{64}$ ]]; then
    echo "[错误] extract-wrapper-body.mjs 未产出合法 sha256（got: '${body_sha}'），source: $source_skill_path" >&2
    exit 1
  fi

  cat <<EOF_CONTRACT
## Wrapper Source Contract

- Canonical source: \`\$PLUGIN_DIR/skills/$source_skill_name/SKILL.md\`
- Source SHA256: $body_sha
- Generated by: \`bash \$PLUGIN_DIR/scripts/codex-skills.sh install\`
- Contract: \`\$PLUGIN_DIR/contracts/wrapper-source-of-truth.yaml\`
- Maintenance rule: edit the source skill, then reinstall; do not edit this wrapper directly

---
EOF_CONTRACT
}

write_skill_body() {
  local source_skill_path="$1"

  # F186 T2：frontmatter 剥除 + runtime text 替换改由单一 Node helper 产出，
  # 与 validate-wrapper-sources.mjs 共用同一提取逻辑（防双实现逐字节漂移）。
  local body
  body="$(node "$PLUGIN_DIR/scripts/lib/extract-wrapper-body.mjs" "$source_skill_path")"

  # CRITICAL-1：helper 误判 isDirectExecution（含空格/非 ASCII 安装路径）时会输出空 body 但退出码 0，
  # 静默生成空正文 wrapper。source skill 正文恒非空，故空 body 必为 helper 故障 → hard fail。
  if [[ -z "$body" ]]; then
    echo "[错误] extract-wrapper-body.mjs 产出空 body，source: $source_skill_path" >&2
    exit 1
  fi
  printf '%s\n' "$body"
}

write_wrapper() {
  local skill_name="$1"
  local source_skill_name="$2"
  local source_skill_path="$PLUGIN_DIR/skills/$source_skill_name/SKILL.md"
  local target_file="$TARGET_DIR/$skill_name/SKILL.md"

  ensure_source_exists "$source_skill_path"
  mkdir -p "$(dirname "$target_file")"

  {
    write_frontmatter "$skill_name" "$source_skill_path"
    printf '\n'
    write_wrapper_source_contract "$source_skill_name" "$source_skill_path"
    printf '\n'
    write_codex_adapter "$skill_name" "$source_skill_name"
    printf '\n'
    write_skill_body "$source_skill_path"
  } > "$target_file"
}

# Feature 213（A1）：copy-after-generate 把已生成的 $TARGET_DIR 内各 skill 目录复制到
# tracked 的 $PLUGIN_DIR/skills-codex/，保证与 .codex/skills 逐字节相同（含内嵌 Source SHA256 行）。
# 选 copy 而非二次 write_wrapper：避免未来单独改一处生成逻辑造成漂移，也少一半子进程调用。
sync_plugin_distribution_copy() {
  local dist_dir="$PLUGIN_DIR/skills-codex"
  rm -rf "$dist_dir"
  mkdir -p "$dist_dir"
  for skill in "${SKILLS[@]}"; do
    cp -R "$TARGET_DIR/$skill" "$dist_dir/$skill"
  done
  echo "Spec Driver Codex skills 已同步到分发目录: $dist_dir"
}

install_all() {
  write_wrapper "spec-driver-constitution" "spec-driver-constitution"
  write_wrapper "spec-driver-feature" "spec-driver-feature"
  write_wrapper "spec-driver-implement" "spec-driver-implement"
  write_wrapper "spec-driver-story" "spec-driver-story"
  write_wrapper "spec-driver-fix" "spec-driver-fix"
  write_wrapper "spec-driver-resume" "spec-driver-resume"
  write_wrapper "spec-driver-sync" "spec-driver-sync"
  write_wrapper "spec-driver-doc" "spec-driver-doc"
  write_wrapper "spec-driver-refactor" "spec-driver-refactor"

  # Feature 238（Slice 3/FR-201/206/208）：单次 capability 探测 + sidecar 写入。
  # sidecar 是本地运行态诊断产物（gitignored，见 .gitignore），与上面 9 个 tracked
  # wrapper 生成逻辑彻底解耦——探测/写入失败仅告警，不阻断 install（FR-202/E1/E2）。
  #
  # W5（Codex implement 审查修复轮，sidecar 原子写）：先写临时文件，成功且非空才
  # `mv -f` 覆盖正式路径；任一环节失败则清理临时文件并删除旧 sidecar（而非保留
  # 陈旧/半截内容），回到 wrapper 文案已定义的"记录缺失→降级为内联/串行执行"语义，
  # 杜绝直接重定向可能产生的零字节/半截文件第三态。
  local sidecar_path sidecar_tmp
  sidecar_path="$(dirname "$TARGET_DIR")/spec-driver-capability.md"
  sidecar_tmp="${sidecar_path}.tmp.$$"
  if node "$PLUGIN_DIR/scripts/lib/detect-codex-capability.mjs" --markdown > "$sidecar_tmp" 2>/dev/null && [[ -s "$sidecar_tmp" ]]; then
    mv -f "$sidecar_tmp" "$sidecar_path"
  else
    rm -f "$sidecar_tmp" "$sidecar_path"
    echo "[警告] capability 探测/sidecar 写入失败，已清除记录（降级为记录缺失语义），不阻断 install" >&2
  fi

  # opt-in：仅显式 --sync-plugin-distribution 时才重写 tracked skills-codex/，
  # 避免测试套件以 cwd=tempDir 反复调用真实脚本时误删/重写真实工作树内容。
  if [[ "$SYNC_PLUGIN_DIST" == "true" ]]; then
    sync_plugin_distribution_copy
  fi

  echo "Spec Driver Codex skills 安装完成: $TARGET_DIR"
}

# W2 修订：`[[ -d "$dir" ]]` 对「不存在」与「无权限」返回同一个 false，
# 于是不可访问的安装目录被当成"没装过" → 输出"无需清理"（卸载假成功，产物其实还在磁盘上）。
# bash 拿不到 errno，故改为按**可判定性**分流：只有在能确定"父目录可搜索、目标目录可读可搜索"
# 的前提下，`[[ -d ]]` 的 false 才真正代表"不存在"；否则一律 fail-loud，绝不冒充"无需清理"。
#
# 诚实标注适用范围：这里只检查 TARGET_DIR 及其**直接父目录**两级（即 CODEX_HOME 与
# CODEX_HOME/skills），不做递归祖先遍历——这两级正是本脚本自身创建与写入的层级，
# 更上层不可达属环境级异常，此时 `[[ ! -e ]]` 仍可能误判为 missing，非本修复覆盖面。
# Node 侧（skill-installer.ts）走的是真实 errno 分流，判定能力强于此处。
probe_removal_root() {
  local root="$1"
  local parent
  parent="$(dirname "$root")"

  if [[ -e "$parent" && ! -x "$parent" ]]; then
    printf '%s\n' "denied-parent"
    return 0
  fi
  if [[ ! -e "$root" ]]; then
    printf '%s\n' "missing"
    return 0
  fi
  if [[ ! -d "$root" ]]; then
    printf '%s\n' "not-a-directory"
    return 0
  fi
  # 目录存在但不可读/不可搜索时无法枚举子目录，下面的 `[[ -d ]]` 会一律 false
  if [[ ! -r "$root" || ! -x "$root" ]]; then
    printf '%s\n' "denied"
    return 0
  fi
  printf '%s\n' "ok"
}

remove_all() {
  local root_state
  root_state="$(probe_removal_root "$TARGET_DIR")"
  case "$root_state" in
    denied-parent)
      echo "[错误] 无法判定是否已安装：$TARGET_DIR 的父目录不可搜索（权限不足），这不等于「未安装」。请检查目录权限后重试" >&2
      exit 1
      ;;
    denied)
      echo "[错误] 无法枚举已安装内容：$TARGET_DIR 不可读或不可搜索（权限不足），这不等于「未安装」。请检查目录权限后重试" >&2
      exit 1
      ;;
    not-a-directory)
      echo "[错误] $TARGET_DIR 存在但不是目录，拒绝在此执行清理" >&2
      exit 1
      ;;
    missing)
      echo "未检测到已安装的 Spec Driver Codex skills，无需清理"
      return 0
      ;;
  esac

  local removed=0
  for skill in "${SKILLS[@]}"; do
    local dir="$TARGET_DIR/$skill"
    if [[ -d "$dir" ]]; then
      rm -rf "$dir"
      echo "✓ 已删除: $dir"
      removed=$((removed + 1))
    fi
  done

  if [[ $removed -eq 0 ]]; then
    echo "未检测到已安装的 Spec Driver Codex skills，无需清理"
  else
    echo "Spec Driver Codex skills 已移除: $removed 个"
  fi
}

if [[ "$ACTION" == "install" ]]; then
  install_all
else
  remove_all
fi
