/**
 * Spec Driver Codex skills 安装脚本集成测试
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { resolve, join } from 'node:path';
import { mkdtempSync, rmSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';

const SCRIPT_PATH = resolve('plugins/spec-driver/scripts/codex-skills.sh');

function runScript(
  args: string[],
  options?: { cwd?: string; home?: string },
): { stdout: string; exitCode: number } {
  try {
    const stdout = execFileSync('bash', [SCRIPT_PATH, ...args], {
      encoding: 'utf-8',
      timeout: 10_000,
      cwd: options?.cwd ?? process.cwd(),
      env: {
        ...process.env,
        HOME: options?.home ?? process.env['HOME'],
      },
    });
    return { stdout, exitCode: 0 };
  } catch (err: unknown) {
    const error = err as { stdout?: string; stderr?: string; status?: number };
    return {
      stdout: (error.stdout ?? '') + (error.stderr ?? ''),
      exitCode: error.status ?? 1,
    };
  }
}

describe('Spec Driver Codex skills script', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'spec-driver-codex-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('project 安装并移除 codex 包装技能', () => {
    const install = runScript(['install'], { cwd: tempDir });
    expect(install.exitCode).toBe(0);
    expect(install.stdout).toContain('安装完成');

    expect(
      existsSync(
        join(tempDir, '.codex', 'skills', 'spec-driver-feature', 'SKILL.md'),
      ),
    ).toBe(true);
    expect(
      existsSync(
        join(tempDir, '.codex', 'skills', 'spec-driver-implement', 'SKILL.md'),
      ),
    ).toBe(true);
    expect(
      existsSync(join(tempDir, '.codex', 'skills', 'spec-driver-doc', 'SKILL.md')),
    ).toBe(true);
    expect(
      existsSync(
        join(tempDir, '.codex', 'skills', 'spec-driver-constitution', 'SKILL.md'),
      ),
    ).toBe(true);

    const storyWrapper = readFileSync(
      join(tempDir, '.codex', 'skills', 'spec-driver-story', 'SKILL.md'),
      'utf-8',
    );
    expect(storyWrapper).toContain('description: "快速需求实现');
    expect(storyWrapper).toContain('## Wrapper Source Contract');
    expect(storyWrapper).toContain('## Codex Runtime Adapter');
    expect(storyWrapper).toContain('Canonical source: `$PLUGIN_DIR/skills/spec-driver-story/SKILL.md`');
    expect(storyWrapper).toContain('Generated by: `bash $PLUGIN_DIR/scripts/codex-skills.sh install`');
    expect(storyWrapper).toContain('Contract: `$PLUGIN_DIR/contracts/wrapper-source-of-truth.yaml`');
    expect(storyWrapper).toContain('do not edit this wrapper directly');
    expect(storyWrapper).toContain('$spec-driver-story <需求描述>');
    expect(storyWrapper).toContain('model_compat.defaults.codex');
    expect(storyWrapper).toContain('opus/sonnet');
    expect(storyWrapper).toContain('.specify/project-context.yaml');
    expect(storyWrapper).toContain('resolve-project-context.mjs');
    expect(storyWrapper).toContain('canonical source');
    expect(storyWrapper).toContain('legacy fallback');
    expect(storyWrapper).toContain('架构合理性');
    expect(storyWrapper).toContain('可读性');

    const implementWrapper = readFileSync(
      join(tempDir, '.codex', 'skills', 'spec-driver-implement', 'SKILL.md'),
      'utf-8',
    );
    expect(implementWrapper).toContain('description: "成熟 Spec 实施');
    expect(implementWrapper).toContain('## Wrapper Source Contract');
    expect(implementWrapper).toContain('Canonical source: `$PLUGIN_DIR/skills/spec-driver-implement/SKILL.md`');
    expect(implementWrapper).toContain('$spec-driver-implement [<feature-dir-or-id>]');
    expect(implementWrapper).toContain('成熟 `spec.md + plan.md` 的聚焦实施');
    expect(implementWrapper).toContain('Spec / Plan 合同检查（Implement 首要前置 gate）');
    expect(implementWrapper).toContain('[CONTRACT_CHECK] READY|BLOCKED');
    expect(implementWrapper).toContain('resolve-project-context.mjs');
    expect(implementWrapper).toContain('.specify/project-context.yaml');
    expect(implementWrapper).toContain('.specify/project-context.suggestions.yaml');
    expect(implementWrapper).toContain('advisory-only');
    expect(implementWrapper).toContain('架构合理性');
    expect(implementWrapper).toContain('可读性');

    const constitutionWrapper = readFileSync(
      join(tempDir, '.codex', 'skills', 'spec-driver-constitution', 'SKILL.md'),
      'utf-8',
    );
    expect(constitutionWrapper).toContain('$spec-driver-constitution [原则更新说明]');
    expect(constitutionWrapper).toContain('.specify/memory/constitution.md');

    const remove = runScript(['remove'], { cwd: tempDir });
    expect(remove.exitCode).toBe(0);
    expect(remove.stdout).toContain('已移除');
    expect(
      existsSync(join(tempDir, '.codex', 'skills', 'spec-driver-feature')),
    ).toBe(false);
  });

  it('global 模式写入 HOME/.codex/skills（隔离 HOME）', () => {
    const fakeHome = join(tempDir, 'fake-home');
    const result = runScript(['install', '--global'], {
      cwd: tempDir,
      home: fakeHome,
    });

    expect(result.exitCode).toBe(0);
    expect(
      existsSync(join(fakeHome, '.codex', 'skills', 'spec-driver-sync', 'SKILL.md')),
    ).toBe(true);
    expect(
      existsSync(join(fakeHome, '.codex', 'skills', 'spec-driver-implement', 'SKILL.md')),
    ).toBe(true);
    expect(
      existsSync(
        join(fakeHome, '.codex', 'skills', 'spec-driver-constitution', 'SKILL.md'),
      ),
    ).toBe(true);

    const wrapperContent = readFileSync(
      join(fakeHome, '.codex', 'skills', 'spec-driver-feature', 'SKILL.md'),
      'utf-8',
    );
    expect(wrapperContent).toContain('description: "执行 Spec-Driven Development 完整研发流程');
    expect(wrapperContent).toContain('## Wrapper Source Contract');
    expect(wrapperContent).toContain('## Codex Runtime Adapter');
    expect(wrapperContent).toContain('$PLUGIN_DIR/skills/spec-driver-feature/SKILL.md');
    expect(wrapperContent).toContain('$PLUGIN_DIR/contracts/wrapper-source-of-truth.yaml');
    expect(wrapperContent).toContain('$spec-driver-feature <需求描述>');
    expect(wrapperContent).toContain('# Spec Driver — 自治研发编排器');
    expect(wrapperContent).toContain('.specify/project-context.suggestions.yaml');
    expect(wrapperContent).toContain('advisory-only');
    expect(wrapperContent).toContain('架构合理性');
    expect(wrapperContent).toContain('可读性');
    expect(wrapperContent).not.toContain(
      resolve('plugins/spec-driver/skills/spec-driver-feature/SKILL.md'),
    );
  });

  it('project 模式在 git 子目录执行时安装到 git 根目录', () => {
    const repoRoot = join(tempDir, 'repo');
    mkdirSync(repoRoot, { recursive: true });
    execFileSync('git', ['init'], { cwd: repoRoot, encoding: 'utf-8' });
    const nestedCwd = join(repoRoot, 'apps', 'web');
    mkdirSync(nestedCwd, { recursive: true });

    const result = runScript(['install'], { cwd: nestedCwd });
    expect(result.exitCode).toBe(0);
    expect(
      existsSync(join(repoRoot, '.codex', 'skills', 'spec-driver-feature', 'SKILL.md')),
    ).toBe(true);
  });
});
