/**
 * Spec Driver Codex skills 安装脚本集成测试
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { resolve, join } from 'node:path';
import {
  mkdtempSync,
  rmSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  cpSync,
  readdirSync,
  statSync,
} from 'node:fs';
import { tmpdir } from 'node:os';

const SCRIPT_PATH = resolve('plugins/spec-driver/scripts/codex-skills.sh');

// Feature 213（T003）：8 个 Spec Driver Codex 适配 skill id（与 wrapper-source-of-truth.yaml entries 对齐）
const SPEC_DRIVER_SKILLS = [
  'spec-driver-constitution',
  'spec-driver-feature',
  'spec-driver-implement',
  'spec-driver-story',
  'spec-driver-fix',
  'spec-driver-resume',
  'spec-driver-sync',
  'spec-driver-doc',
];

// 真实仓库内 tracked 的 Codex 分发目录（无 flag 守护用例锚定其零变化）
const REPO_SKILLS_CODEX = resolve('plugins/spec-driver/skills-codex');

// 计算目录确定性快照：不存在返回 '<absent>'，存在则递归拼接 sorted 相对路径 + 内容
function snapshotDir(dir: string): string {
  if (!existsSync(dir)) {
    return '<absent>';
  }
  const entries: string[] = [];
  const walk = (current: string, rel: string): void => {
    for (const name of readdirSync(current).sort()) {
      const full = join(current, name);
      const relPath = rel ? `${rel}/${name}` : name;
      if (statSync(full).isDirectory()) {
        walk(full, relPath);
      } else {
        entries.push(`${relPath}\n${readFileSync(full, 'utf-8')}`);
      }
    }
  };
  walk(dir, '');
  return entries.join('\n---ENTRY---\n');
}

// 在 tempDir 内建立 plugins/spec-driver 的 fixture 副本（$PLUGIN_DIR 由脚本物理位置派生，
// 用副本脚本可让 skills-codex/ 落在 tempDir 内而非真实仓库）
function copyPluginFixture(root: string): string {
  mkdirSync(join(root, 'plugins'), { recursive: true });
  cpSync(resolve('plugins/spec-driver'), join(root, 'plugins', 'spec-driver'), {
    recursive: true,
  });
  return join(root, 'plugins', 'spec-driver', 'scripts', 'codex-skills.sh');
}

// 运行任意路径脚本（catch 非零退出，用于 TDD 红用例断言 exitCode）
function runFixtureScript(
  scriptPath: string,
  args: string[],
  root: string,
): { stdout: string; exitCode: number } {
  try {
    const stdout = execFileSync('bash', [scriptPath, ...args], {
      encoding: 'utf-8',
      timeout: 20_000,
      cwd: root,
      env: {
        ...process.env,
        HOME: process.env['HOME'],
        CODEX_SKILL_PROJECT_ROOT: root,
      },
    });
    return { stdout, exitCode: 0 };
  } catch (err: unknown) {
    const error = err as { stdout?: string; stderr?: string; status?: number };
    return {
      stdout: (error.stdout ?? '') + (error.stderr ?? ''),
      exitCode: error.status ?? 1,
    };
  }
}

function runScript(
  args: string[],
  options?: { cwd?: string; home?: string },
): { stdout: string; exitCode: number } {
  try {
    const stdout = execFileSync('bash', [SCRIPT_PATH, ...args], {
      encoding: 'utf-8',
      timeout: 10_000,
      cwd: options?.cwd ?? process.cwd(),
      env: {
        ...process.env,
        HOME: options?.home ?? process.env['HOME'],
      },
    });
    return { stdout, exitCode: 0 };
  } catch (err: unknown) {
    const error = err as { stdout?: string; stderr?: string; status?: number };
    return {
      stdout: (error.stdout ?? '') + (error.stderr ?? ''),
      exitCode: error.status ?? 1,
    };
  }
}

describe('Spec Driver Codex skills script', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'spec-driver-codex-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('project 安装并移除 codex 包装技能', () => {
    const install = runScript(['install'], { cwd: tempDir });
    expect(install.exitCode).toBe(0);
    expect(install.stdout).toContain('安装完成');

    expect(
      existsSync(
        join(tempDir, '.codex', 'skills', 'spec-driver-feature', 'SKILL.md'),
      ),
    ).toBe(true);
    expect(
      existsSync(
        join(tempDir, '.codex', 'skills', 'spec-driver-implement', 'SKILL.md'),
      ),
    ).toBe(true);
    expect(
      existsSync(join(tempDir, '.codex', 'skills', 'spec-driver-doc', 'SKILL.md')),
    ).toBe(true);
    expect(
      existsSync(
        join(tempDir, '.codex', 'skills', 'spec-driver-constitution', 'SKILL.md'),
      ),
    ).toBe(true);

    const storyWrapper = readFileSync(
      join(tempDir, '.codex', 'skills', 'spec-driver-story', 'SKILL.md'),
      'utf-8',
    );
    expect(storyWrapper).toContain('description: "快速需求实现');
    expect(storyWrapper).toContain('## Wrapper Source Contract');
    expect(storyWrapper).toContain('## Codex Runtime Adapter');
    expect(storyWrapper).toContain('Canonical source: `$PLUGIN_DIR/skills/spec-driver-story/SKILL.md`');
    expect(storyWrapper).toContain('Generated by: `bash $PLUGIN_DIR/scripts/codex-skills.sh install`');
    expect(storyWrapper).toContain('Contract: `$PLUGIN_DIR/contracts/wrapper-source-of-truth.yaml`');
    expect(storyWrapper).toContain('do not edit this wrapper directly');
    expect(storyWrapper).toContain('$spec-driver-story <需求描述>');
    expect(storyWrapper).toContain('model_compat.defaults.codex');
    expect(storyWrapper).toContain('opus/sonnet');
    expect(storyWrapper).toContain('.specify/project-context.yaml');
    expect(storyWrapper).toContain('resolve-project-context.mjs');
    expect(storyWrapper).toContain('canonical source');
    expect(storyWrapper).toContain('legacy fallback');
    expect(storyWrapper).toContain('架构合理性');
    expect(storyWrapper).toContain('可读性');

    const implementWrapper = readFileSync(
      join(tempDir, '.codex', 'skills', 'spec-driver-implement', 'SKILL.md'),
      'utf-8',
    );
    expect(implementWrapper).toContain('description: "成熟 Spec 实施');
    expect(implementWrapper).toContain('## Wrapper Source Contract');
    expect(implementWrapper).toContain('Canonical source: `$PLUGIN_DIR/skills/spec-driver-implement/SKILL.md`');
    expect(implementWrapper).toContain('$spec-driver-implement [<feature-dir-or-id>]');
    expect(implementWrapper).toContain('成熟 `spec.md + plan.md` 的聚焦实施');
    expect(implementWrapper).toContain('Spec / Plan 合同检查（Implement 首要前置 gate）');
    expect(implementWrapper).toContain('[CONTRACT_CHECK] READY|BLOCKED');
    expect(implementWrapper).toContain('resolve-project-context.mjs');
    expect(implementWrapper).toContain('.specify/project-context.yaml');
    expect(implementWrapper).toContain('.specify/project-context.suggestions.yaml');
    expect(implementWrapper).toContain('advisory-only');
    expect(implementWrapper).toContain('架构合理性');
    expect(implementWrapper).toContain('可读性');

    const constitutionWrapper = readFileSync(
      join(tempDir, '.codex', 'skills', 'spec-driver-constitution', 'SKILL.md'),
      'utf-8',
    );
    expect(constitutionWrapper).toContain('$spec-driver-constitution [原则更新说明]');
    expect(constitutionWrapper).toContain('.specify/memory/constitution.md');

    const remove = runScript(['remove'], { cwd: tempDir });
    expect(remove.exitCode).toBe(0);
    expect(remove.stdout).toContain('已移除');
    expect(
      existsSync(join(tempDir, '.codex', 'skills', 'spec-driver-feature')),
    ).toBe(false);
  });

  it('global 模式写入 HOME/.codex/skills（隔离 HOME）', () => {
    const fakeHome = join(tempDir, 'fake-home');
    const result = runScript(['install', '--global'], {
      cwd: tempDir,
      home: fakeHome,
    });

    expect(result.exitCode).toBe(0);
    expect(
      existsSync(join(fakeHome, '.codex', 'skills', 'spec-driver-sync', 'SKILL.md')),
    ).toBe(true);
    expect(
      existsSync(join(fakeHome, '.codex', 'skills', 'spec-driver-implement', 'SKILL.md')),
    ).toBe(true);
    expect(
      existsSync(
        join(fakeHome, '.codex', 'skills', 'spec-driver-constitution', 'SKILL.md'),
      ),
    ).toBe(true);

    const wrapperContent = readFileSync(
      join(fakeHome, '.codex', 'skills', 'spec-driver-feature', 'SKILL.md'),
      'utf-8',
    );
    expect(wrapperContent).toContain('description: "执行 Spec-Driven Development 完整研发流程');
    expect(wrapperContent).toContain('## Wrapper Source Contract');
    expect(wrapperContent).toContain('## Codex Runtime Adapter');
    expect(wrapperContent).toContain('$PLUGIN_DIR/skills/spec-driver-feature/SKILL.md');
    expect(wrapperContent).toContain('$PLUGIN_DIR/contracts/wrapper-source-of-truth.yaml');
    expect(wrapperContent).toContain('$spec-driver-feature <需求描述>');
    expect(wrapperContent).toContain('# Spec Driver — 自治研发编排器');
    // Feature SKILL.md 在 Feature 089 编排拆分后不再包含 suggestions/审查维度等引用
    // 这些内容已拆分到独立的 agent prompt 中，不再内嵌于 SKILL.md
    expect(wrapperContent).not.toContain(
      resolve('plugins/spec-driver/skills/spec-driver-feature/SKILL.md'),
    );
  });

  it('project 模式在 git 子目录执行时安装到 git 根目录', () => {
    const repoRoot = join(tempDir, 'repo');
    mkdirSync(repoRoot, { recursive: true });
    execFileSync('git', ['init'], { cwd: repoRoot, encoding: 'utf-8' });
    const nestedCwd = join(repoRoot, 'apps', 'web');
    mkdirSync(nestedCwd, { recursive: true });

    const result = runScript(['install'], { cwd: nestedCwd });
    expect(result.exitCode).toBe(0);
    expect(
      existsSync(join(repoRoot, '.codex', 'skills', 'spec-driver-feature', 'SKILL.md')),
    ).toBe(true);
  });

  // Feature 213 T003：opt-in 双写机制（一红两绿）
  describe('Feature 213 — --sync-plugin-distribution opt-in 双写', () => {
    it('[红] install --sync-plugin-distribution 生成 skills-codex/ 8 目录且与 .codex/skills 字节相同', () => {
      const fixtureScript = copyPluginFixture(tempDir);
      const install = runFixtureScript(
        fixtureScript,
        ['install', '--sync-plugin-distribution'],
        tempDir,
      );
      // 实现前：脚本无该 flag → 未知参数 exit 1 → 本断言失败（红）
      expect(install.exitCode).toBe(0);

      const distDir = join(tempDir, 'plugins', 'spec-driver', 'skills-codex');
      const codexDir = join(tempDir, '.codex', 'skills');
      expect(existsSync(distDir)).toBe(true);
      expect(readdirSync(distDir).filter((n) => statSync(join(distDir, n)).isDirectory()).sort())
        .toHaveLength(8);
      for (const skill of SPEC_DRIVER_SKILLS) {
        const distFile = join(distDir, skill, 'SKILL.md');
        const codexFile = join(codexDir, skill, 'SKILL.md');
        expect(existsSync(distFile)).toBe(true);
        expect(existsSync(codexFile)).toBe(true);
        // copy-after-generate 保证逐字节相同（Buffer 相等）
        expect(readFileSync(distFile).equals(readFileSync(codexFile))).toBe(true);
      }
    });

    // sentinel 不在 SKILLS 列表内：任何 rm -rf 重建（哪怕字节相同重写）都会丢掉它，
    // 故 sentinel 存活是比"快照字节相同"更强的守护（防"删了又重建相同字节"骗过快照）。
    it('[绿a·characterization] 无 flag 的 install 不触碰 distribution 目录（sentinel 存活 + 真实仓库快照不变）', () => {
      const fixtureScript = copyPluginFixture(tempDir);
      const distDir = join(tempDir, 'plugins', 'spec-driver', 'skills-codex');
      mkdirSync(distDir, { recursive: true });
      const sentinel = join(distDir, '.sentinel-do-not-touch');
      writeFileSync(sentinel, 'SENTINEL');

      const repoBefore = snapshotDir(REPO_SKILLS_CODEX);
      const install = runFixtureScript(fixtureScript, ['install'], tempDir);
      expect(install.exitCode).toBe(0);

      // sentinel 存活（若 sync_plugin_distribution_copy 的 rm -rf 误触发会删掉它）
      expect(existsSync(sentinel)).toBe(true);
      expect(readFileSync(sentinel, 'utf-8')).toBe('SENTINEL');
      // 第二道防线：真实仓库 skills-codex 快照不变
      expect(snapshotDir(REPO_SKILLS_CODEX)).toBe(repoBefore);
    });

    it('[绿b·characterization] remove 不触碰 distribution 目录（sentinel 存活 + 真实仓库快照不变）', () => {
      const fixtureScript = copyPluginFixture(tempDir);
      const distDir = join(tempDir, 'plugins', 'spec-driver', 'skills-codex');
      mkdirSync(distDir, { recursive: true });
      const sentinel = join(distDir, '.sentinel-do-not-touch');
      writeFileSync(sentinel, 'SENTINEL');

      const repoBefore = snapshotDir(REPO_SKILLS_CODEX);
      runFixtureScript(fixtureScript, ['install'], tempDir);
      const remove = runFixtureScript(fixtureScript, ['remove'], tempDir);
      expect(remove.exitCode).toBe(0);

      expect(existsSync(sentinel)).toBe(true);
      expect(readFileSync(sentinel, 'utf-8')).toBe('SENTINEL');
      expect(snapshotDir(REPO_SKILLS_CODEX)).toBe(repoBefore);
    });
  });
});
